stages:
  prepare:
    cmd: python mlops_imdb/data/prepare.py
    deps:
    - mlops_imdb/data/prepare.py
    - data/raw/imdb_test.csv
    - data/raw/imdb_train.csv
    params:
    - data
    - preprocessing
    - random_seed
    outs:
    - data/processed/imdb_test_clean.csv
    - data/processed/imdb_train_clean.csv
  spam_prepare:
    cmd: python mlops_imdb/spam/prepare.py
    deps:
    - mlops_imdb/spam/prepare.py
    - data/raw/spam_train.parquet
    - data/raw/spam_test.parquet
    params:
    - spam.data
    - spam.preprocessing
    outs:
    - data/processed/spam_train_clean.csv
    - data/processed/spam_test_clean.csv
  spam_features:
    cmd: python mlops_imdb/spam/features.py
    deps:
    - data/processed/spam_train_clean.csv
    - data/processed/spam_test_clean.csv
    - mlops_imdb/spam/features.py
    params:
    - spam.features
    outs:
    - data/processed/spam_train_features.pt
    - data/processed/spam_test_features.pt
    - models/spam_vocab.json
  spam_train:
    cmd: python mlops_imdb/spam/train.py
    deps:
    - data/processed/spam_train_features.pt
    - models/spam_vocab.json
    - mlops_imdb/spam/model.py
    - mlops_imdb/spam/train.py
    params:
    - random_seed
    - spam.train
    outs:
    - models/spam_model.pt
    - reports/figures/spam_training_loss.png
  spam_eval:
    cmd: python mlops_imdb/spam/eval.py
    deps:
    - data/processed/spam_test_features.pt
    - models/spam_model.pt
    - models/spam_vocab.json
    - mlops_imdb/spam/model.py
    - mlops_imdb/spam/eval.py
    params:
    - spam.eval
    - spam.train
    metrics:
    - reports/spam_metrics.json:
        cache: false
    outs:
    - reports/figures/spam_confusion_matrix.png
