# MLOps IMDb Sentiment Analysis - Pipeline Parameters
random_seed: 42

data:
  raw:
    train: data/raw/imdb_train.csv
    test: data/raw/imdb_test.csv
  processed:
    train: data/processed/imdb_train_clean.csv
    test: data/processed/imdb_test_clean.csv
  split_info: data/split_info.json
  schema:
    text_col: text
    label_col: label
    label_domain: [0, 1]
  split:
    strategy: fixed_from_split_info
    train_ratio: 0.5

preprocessing:
  lowercase: true
  remove_html_tags: true
  normalize_whitespace: true
  # No stemming/lemmatization/stopwords (deferred)

features:
  vectorizer: tfidf
  tfidf:
    max_features: 10000
    ngram_range: [1, 2]
    min_df: 2
    max_df: 0.95
  outputs:
    train_features: data/processed/imdb_train_features.npz
    test_features: data/processed/imdb_test_features.npz
    vectorizer_path: models/tfidf_vectorizer.pkl

train:
  model_type: logistic_regression
  logreg:
    max_iter: 1000
    random_state: 42
  outputs:
    model_path: models/model.pkl

eval:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
  outputs:
    metrics_json: reports/metrics.json
    confusion_matrix_png: reports/figures/baseline_confusion_matrix.png

predict:
  outputs:
    predictions_path: data/processed/test_predictions.csv

qa:
  thresholds:
    min_accuracy: 0.85
    min_f1: 0.85
  baseline_reference: reports/baseline_metrics.json
  data_checks:
    enforce_schema: true
    allow_null_texts: false
    allow_null_labels: false

# TODO
mlflow:
  experiment_name: imdb_sentiment_analysis
  tracking_uri: "file:mlruns"

energy:
  codecarbon:
    enabled: true
    output: reports/codecarbon_emissions.csv

monitoring:
  enabled: true
  drift_detection:
    enabled: true
    p_threshold: 0.05
    detector_type: ks 
    min_samples: 50
    window_size: 500
    sample_size: 1000
  prediction_monitoring:
    enabled: true
    window_size: 1000
    confidence_threshold: 0.6
    positive_ratio_warning: 0.3
    positive_ratio_critical: 0.2
  alerting:
    enabled: true
    log_alerts: true
  outputs:
    drift_detector_path: models/drift_detector
    prediction_monitor_path: models/prediction_monitor

stages:
  prepare: true
  features: true
  train: true
  eval: true
  predict: false
  spam_prepare: true
  spam_features: true
  spam_train: true
  spam_eval: true

spam:
  data:
    raw:
      train: data/raw/spam_train.parquet
      test: data/raw/spam_test.parquet
    processed:
      train: data/processed/spam_train_clean.csv
      test: data/processed/spam_test_clean.csv
    schema:
      text_col: text
      label_col: label
      label_domain: [0, 1]
      label_mapping:
        spam: 1
        not_spam: 0
  preprocessing:
    lowercase: true
    remove_html_tags: true
    decode_html_entities: true
    normalize_whitespace: true
  features:
    max_len: 50
    min_freq: 1
    pad_token: "<PAD>"
    unk_token: "<UNK>"
    text_column: clean_text
    outputs:
      train_tensor: data/processed/spam_train_features.pt
      test_tensor: data/processed/spam_test_features.pt
      vocab_path: models/spam_vocab.json
  train:
    embedding_dim: 64
    hidden_dim: 64
    dropout: 0.0
    batch_size: 32
    epochs: 5
    learning_rate: 0.001
    outputs:
      model_path: models/spam_model.pt
      training_curve_png: reports/figures/spam_training_loss.png
  eval:
    batch_size: 64
    outputs:
      metrics_json: reports/spam_metrics.json
      confusion_matrix_png: reports/figures/spam_confusion_matrix.png
