{
 "title": "MLOps_IMDb",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Spam Inference API Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (app, status_type) (\r\n  count_over_time(\r\n    {container=~\".*spam-api.*\"}\r\n    |= \"/predict\"\r\n    | regexp \"HTTP/1.1\\\" (?P<class>[245])[0-9]{2}\"\r\n    | label_format app=\"{{if (contains .container `spam-api`)}}spam-api{{else}}sentiment-api{{end}}\",\r\n                   status_type=\"{{if eq .class `2`}}ok{{else}}error{{end}}\"\r\n  [1m])\r\n)"
    }
   ]
  },
  {
   "title": "Sentiment Inference API Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (app, status_type) (\r\n  count_over_time(\r\n    {container=~\".*sentiment-api.*\"}\r\n    |= \"/predict\"\r\n    | regexp \"HTTP/1.1\\\" (?P<class>[245])[0-9]{2}\"\r\n    | label_format app=\"{{if (contains .container `spam-api`)}}spam-api{{else}}sentiment-api{{end}}\",\r\n                   status_type=\"{{if eq .class `2`}}ok{{else}}error{{end}}\"\r\n  [1m])\r\n)"
    }
   ]
  },
  {
   "title": "Spam Model Updater",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"deployment-spam-model-updater-1\"} |= \"Local spam_model is up to date\" [$__interval]))",
     "legendFormat": "Up to Date"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"deployment-spam-model-updater-1\"} |= \"spam-api reloaded successfully\" [$__interval]))",
     "legendFormat": "Reloaded"
    }
   ]
  },
  {
   "title": "Sentiment Model Updater",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"deployment-sentiment-model-updater-1\"} |= \"Local sentiment_model is up to date\" [$__interval]))",
     "legendFormat": "Up to Date"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"deployment-sentiment-model-updater-1\"} |= \"sentiment-api reloaded successfully\" [$__interval]))",
     "legendFormat": "Reloaded"
    }
   ]
  },
  {
   "title": "User Sessions UI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (app) (\r\n  count_over_time(\r\n    {container=~\".*ui.*\"}\r\n    |= \"New user session started\"\r\n    | label_format app=\"ui\"\r\n  [1m])\r\n)\r\n"
    }
   ]
  }
 ]
}