name: policy

on:
  pull_request:
    branches: ["main"]

jobs:
  branch-name:
    name: branch-name
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          # Extract PR head ref and validate pattern
          BRANCH="${{ github.head_ref }}"
          echo "Branch: $BRANCH"
          if [[ ! "$BRANCH" =~ ^(feature|fix|chore|docs|experiment)\/[a-z0-9._-]+$ ]]; then
            echo "Invalid branch name. Use feature|fix|chore|docs|experiment/<short-topic>"
            exit 1
          fi

  pr-title:
    name: pr-title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            chore
            test
            refactor
            perf
            build
            ci
            style
            revert

  commit-messages:
    name: commit-messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install gitlint
        run: |
          python -m pip install --upgrade pip
          pip install gitlint
      - name: Lint PR commits with gitlint
        run: gitlint --commits origin/${{ github.base_ref }}..HEAD
